# Lista de codiciones extra que se pueden utilizar en argos_check_competeness

argos_extra_conditions_list <- list(
  targ2_organ = "target_stat == '1' & !is.na(targ3_organ)",
  targ3_organ = "target_stat == '1' & !is.na(targ4_organ)",
  targ4_organ = "target_stat == '1' & !is.na(targ5_organ)",
  targ5_organ = "FALSE",
  targ2_description = "!is.na(targ2_organ)",
  targ3_description = "!is.na(targ3_organ)",
  targ4_description = "!is.na(targ4_organ)",
  targ5_description = "!is.na(targ5_organ)",
  targ2_mm = "!is.na(targ2_organ)",
  targ3_mm = "!is.na(targ3_organ)",
  targ4_mm = "!is.na(targ4_organ)",
  targ5_mm = "!is.na(targ5_organ)",
  notarg1_organ = "notarget_stat == '1' & !is.na(notarg2_organ)",
  notarg2_organ = "notarget_stat == '1' & !is.na(notarg3_organ)",
  notarg3_organ = "notarget_stat == '1' & !is.na(notarg4_organ)",
  notarg4_organ = "notarget_stat == '1' & !is.na(notarg5_organ)",
  notarg5_organ = "notarget_stat == '1' & !is.na(notarg6_organ)",
  notarg6_organ = "notarget_stat == '1' & !is.na(notarg7_organ)",
  notarg7_organ = "notarget_stat == '1' & !is.na(notarg8_organ)",
  notarg8_organ = "notarget_stat == '1' & !is.na(notarg9_organ)",
  notarg9_organ = "notarget_stat == '1' & !is.na(notarg10_organ)",
  notarg10_organ = "FALSE",
  notarg1_description = "!is.na(notarg1_organ)",
  notarg2_description = "!is.na(notarg2_organ)",
  notarg3_description = "!is.na(notarg3_organ)",
  notarg4_description = "!is.na(notarg4_organ)",
  notarg5_description = "!is.na(notarg5_organ)",
  notarg6_description = "!is.na(notarg6_organ)",
  notarg7_description = "!is.na(notarg7_organ)",
  notarg8_description = "!is.na(notarg8_organ)",
  notarg9_description = "!is.na(notarg9_organ)",
  notarg10_description = "!is.na(notarg10_organ)",
  notarg1_stat = "!is.na(notarg1_organ)",
  notarg2_stat = "!is.na(notarg2_organ)",
  notarg3_stat = "!is.na(notarg3_organ)",
  notarg4_stat = "!is.na(notarg4_organ)",
  notarg5_stat = "!is.na(notarg5_organ)",
  notarg6_stat = "!is.na(notarg6_organ)",
  notarg7_stat = "!is.na(notarg7_organ)",
  notarg8_stat = "!is.na(notarg8_organ)",
  notarg9_stat = "!is.na(notarg9_organ)",
  notarg10_stat = "!is.na(notarg10_organ)"
)

usethis::use_data(argos_extra_conditions_list, overwrite = TRUE)
